### ISSUE TITLE
fragmentzip_download_file with compression store will fail

### ISSUE THREAD

**Issue by julioverne** [tihmstar/libfragmentzip#2]
if file have compression store it don't extract.. only work in compression deflate.
i have a fix here by memcpy raw compressed bytes to uncompressed
[https://github.com/julioverne/Ext3nder-Installer/blob/master/postinst-installer/libfragmentzip.c#L288](url)

**Comment by tihmstar** [comment]
If you make a pull reuest, i can merge into main branch ;)
