### ISSUE TITLE
[Note] You forgot to expect msys in configure.ac

### ISSUE THREAD

**Issue by mast3rz3ro** [tihmstar/libfragmentzip#21]
Hi there,

I have found this while i was trying to compile the libfragmentzip

Compiling with Msys2 requires excepting it with configuration file. 

```
configure.ac:line25:
*mingw*)

into:
*mingw*|*msys*)
```

Compiling without expecting msys2 could lead to this error:
```
libtool: undefined symbols not allowed in x86_64-pc-msys shared ... only static will be built
```

**Comment by tihmstar** [comment]
You are absolutely correct!
