### ISSUE TITLE
Severe undefined behavior on Windows(MSYS2)

### ISSUE THREAD

**Issue by Cryptiiiic** [tihmstar/libfragmentzip#22]
When you define your own bool implementation, the msys2 compiler(s) define the bool enum as 4 bytes!
https://github.com/tihmstar/libfragmentzip/blob/2dcd708f838eb2eb7adea1f07a3350a0f9e08faa/include/libfragmentzip/libfragmentzip.h#L40-L43
This causes severe undefined behavior. When doing boolean comparision in eg: tsschecker is_ota param for one of the functions, it returns true because its reading random 2 extra bytes instead of just the boolean value. Those extra bytes can be any memory, one or zero. This is really bad.

Proposed fix:
Why don't you just include stdbool instead?
```
#include <stdbool.h>
```

**Comment by tihmstar** [comment]
I don't quite understand in which cases this would break, but i agree that including `#include <stdbool.h>` is a cleaner solution
